# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: anocir
    main: ./cmd/anocir
    binary: anocir
    env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
  # - id: anocird
  #   main: ./cmd/anocird
  #   binary: anocird
  #   env:
  #     - CGO_ENABLED=1
  #   targets:
  #     - linux_amd64
  #     - linux_arm64
archives:
  - id: anocir
    formats: ["tar.gz"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - anocir
  # - id: anocird
  #   formats: ["tar.gz"]
  #   name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  #   builds:
  #     - anocird

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
