# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: anocir
    main: .
    binary: anocir
    env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
      # - linux_arm64

archives:
  - id: anocir
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - anocir

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
